THEOS_DEVICE_IP = 192.168.4.96
GO_EASY_ON_ME = 1

TARGET := iphone:clang:latest:7.0
INSTALL_TARGET_PROCESSES = SpringBoard

#PACKAGE_VERSION = $(THEOS_PACKAGE_BASE_VERSION)
PACKAGE_VERSION = $(THEOS_PACKAGE_BASE_VERSION)-$(VERSION.INC_BUILD_NUMBER)$(VERSION.EXTRAVERSION)

ARCHS = arm64 arm64e
SDKVERSION = 13.3

TWEAK_NAME = RetroVol

$(TWEAK_NAME)_FILES = $(wildcard *.xm)
$(TWEAK_NAME)_CFLAGS = -fobjc-arc
$(TWEAK_NAME)_EXTRA_FRAMEWORKS += Cephei
$(TWEAK_NAME)_LIBRARIES = colorpicker

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk
SUBPROJECTS += retrovolprefs
include $(THEOS_MAKE_PATH)/aggregate.mk
